# Args for FROM directives
ARG UBUNTU_VER=latest

#
# ---- Base Node image ----
FROM ubuntu:${UBUNTU_VER} AS base
ARG NODE_VER=10
ARG GOLANG_VER=1.11.2

# Copy setup files to the image
COPY bashrc run.sh riffmm-setup.sh /setupfiles/

# run the setup script
RUN chmod +x /setupfiles/*.sh \
    && /setupfiles/riffmm-setup.sh

# create and set working directory owned by non-root user; set that user
WORKDIR /home/mmuser
USER mmuser

# set the GOPATH and the PATH to find the go executables
ENV GOPATH /home/mmuser/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

# Set the default command to run when the container is started
CMD ["./run.sh"]

#
# ---- Development ----
FROM base AS development
LABEL Description="dev: This image runs the mattermost-server and webpack watch of mattermost-webapp"

# This is the development image, set NODE_ENV to reflect that
ENV NODE_ENV=development

# expose port that the mattermost server listens to
EXPOSE 8065

# when a container is started w/ this image the mattermost-webapp repository working
# directory must be bound at /home/mmuser/go/src/github.com/mattermost/mattermost-webapp
# and all dependent packages installed AND the mattermost-server repository working
# directory must be bound at /home/mmuser/go/src/github.com/mattermost/mattermost-server
# for the default command (run) to correctly start the mattermost-webapp
VOLUME ["/home/mmuser/go/src/github.com/mattermost/mattermost-server"]
VOLUME ["/home/mmuser/go/src/github.com/mattermost/mattermost-webapp"]
