---
version: '3'
services:
  certbot:
    image: nginx:latest
    image: '127.0.0.1:5000/rifflearning/certbot:latest'
    build: .
    ports:
      - '80:80'
      - '443:443'
    deploy:
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


