---
version: '3'
services:
  certbot:
    image: '127.0.0.1:5000/rifflearning/certbot:latest'
    build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt-data:/etc/letsencrypt
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  letsencrypt-data:
