---
# Base configuration for the services that are required to run the riff platform
# - the image names are set for pulling from the github package registry where the
#   production images will be pushed. Env vars should be set with the appropriate
#   image tag values.
#   - RIFF_SERVER_TAG
#   - RIFF_RTC_TAG
#   - SIGNALMASTER_TAG
#
#   Note that the image names are overridden when building/running on a dev machine
#   see docker-compose.dev.yml
#
# - this file has no build key for any service so it can also be used as the docker
#   swarm stack deployment base configuration.
version: '3.7'
services:
  pfm-riffdata:
    image: 'docker.pkg.github.com/rifflearning/riff-server/riffdata:${RIFF_SERVER_TAG-latest}'
    hostname: pfm-riffdata
    depends_on:
      - pfm-riffdata-db

  pfm-riffrtc:
    image: 'docker.pkg.github.com/rifflearning/riff-docker/riffrtc:${RIFF_RTC_TAG-latest}'
    depends_on:
      - pfm-redis

  pfm-web:
    image: 'docker.pkg.github.com/rifflearning/riff-docker/pfm-web:${RIFF_RTC_TAG-latest}'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - pfm-riffrtc
      - pfm-riffdata
      - pfm-signalmaster

  pfm-signalmaster:
    image: 'docker.pkg.github.com/rifflearning/signalmaster/signalmaster:${SIGNALMASTER_TAG-latest}'

  pfm-riffdata-db:
    image: mongo:${MONGO_VER-latest}
    volumes:
      - pfm-riffdata-db-data:/data/db
      - pfm-riffdata-db-configdb:/data/configdb

  pfm-redis:
    image: redis:${REDIS_VER-latest}
    volumes:
      - pfm-redis-data:/data

volumes:
  pfm-riffdata-db-data:
  pfm-riffdata-db-configdb:
  pfm-redis-data:
