---
# override/additions to docker-compose.dev.yml for development deployment
# currently only used in one place so not committed.
# I have locally copied the letsencrypt certificates into pfm-web/secrets
# for the domain where this is deployed.
version: '3.7'
services:
  pfm-web:
    volumes:
      - ./pfm-web/secrets:/run/secrets
