---
# override/additions to docker-compose.yml for production
#
# Build key for each service is set for building the production image
# as specified in the base docker-compose.yml.
# The env vars for the git ref should match the vars in the base specifying the
# image tag that will be built.
# - RIFF_SERVER_REF <=> RIFF_SERVER_TAG
# - RIFF_RTC_REF <=> RIFF_RTC_TAG <=> RTC_BUILD_TAG
#
# The rtc-build-image tagged by RTC_BUILD_TAG needs to be created BEFORE the
# riffrtc and web images can be built. `make rtc-build-image`
#
# It's rare that the signalmaster needs to be built so the build key for it
# is commented out.
#
# DevNote: In order to build from a private github repo see https://github.com/docker/compose/issues/3038
#     which states that you can use https://username:password@github.com/username/repo.git
#     and that if you use a github personal access token, you can just use it as the
#     username and leave the password blank. (you can also still put in the username
#     and use the token as the password if you wish)
version: '3.7'
services:
  pfm-riffdata:
    build:
      context: https://${GITHUB_TOKEN:?You must export GITHUB_TOKEN}:@github.com/rifflearning/riff-server.git#${RIFF_SERVER_REF-master}
      dockerfile: Dockerfile
      args:
        NODE_VER: 12
        PORT: 3000

  pfm-riffrtc:
    build:
      context: https://${GITHUB_TOKEN:?You must export GITHUB_TOKEN}:@github.com/rifflearning/riff-rtc.git#${RIFF_RTC_REF-master}
      dockerfile: docker/Dockerfile-prod-server
      args:
        RTC_BUILD_TAG: ${RTC_BUILD_TAG-latest}
        NODE_VER: 12
        PORT: 3001

  pfm-web:
    build:
      context:  pfm-web
      dockerfile: Dockerfile-prod
      args:
        RTC_BUILD_TAG: ${RTC_BUILD_TAG-latest}
        NGINX_VER: latest

# Here's the signalmaster service w/ the build key if needed to build production signalmaster,
# but in general, it should just be pulled
# pfm-signalmaster:
#   build:
#     context: https://github.com/rifflearning/signalmaster.git#${SIGNALMASTER_REF-master}
#     dockerfile: Dockerfile
