---
# Base configuration for the services that are required to run the riff platform
# - the image names are set for pulling from the github package registry where the
#   production images will be pushed. Env vars should be set with the appropriate
#   image tag values.
#   - RIFF_SERVER_TAG
#   - RIFF_RTC_TAG
#
#   Note that the image names are overridden when building/running on a dev machine
#   see docker-compose.dev.yml
#
# - this file has no build key for any service so it can also be used as the docker
#   swarm stack deployment base configuration w/o getting a warning.
version: '3.7'
services:
  pfm-riffcollector:
    image: 'ghcr.io/rifflearning/riffcollector:${RIFFCOLLECTOR_TAG-latest}'
    hostname: pfm-riffcollector
    depends_on:
      - pfm-riffcollector-db
    ports:
      - '3000:3000'

  pfm-riffcollector-db:
    image: mongo:${MONGO_VER-latest}
    volumes:
      - pfm-riffcollector-db-data:/data/db
      - pfm-riffcollector-db-configdb:/data/configdb

  pfm-web:
    image: 'ghcr.io/rifflearning/riff-docker/pfm-web:${RIFF_RTC_TAG-latest}'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - pfm-riffrtc
      - pfm-riffcollector
      - pfm-signalmaster

  pfm-riffrtc:
    image: 'ghcr.io/rifflearning/riff-docker/riffrtc:${RIFF_RTC_TAG-latest}'
    depends_on:
      - pfm-redis

  pfm-signalmaster:
    image: 'ghcr.io/rifflearning/signalmaster/signalmaster:2.1.3'

  pfm-redis:
    image: redis:${REDIS_VER-latest}
    volumes:
      - pfm-redis-data:/data

volumes:
  pfm-riffcollector-db-data:
  pfm-riffcollector-db-configdb:
  pfm-redis-data:
