# Args for FROM directives
ARG NGINX_VER=latest
ARG RTC_BUILD_TAG=latest

#
# ---- Base web-server image ----
FROM nginx:${NGINX_VER} AS base
# Copy the self-signed ssl files
COPY ssl/ /etc/ssl/
# Point the site ssl key and crt to the self-signed ones if the docker secrets aren't loaded.
# Remove any existing sample configurations so they don't get loaded
RUN mkdir -p /run/secrets && \
    ln -s /etc/ssl/private/nginx-selfsigned.key /run/secrets/site.key && \
    ln -s /etc/ssl/certs/nginx-selfsigned.crt /run/secrets/site.crt && \
    rm /etc/nginx/conf.d/*.conf
# Copy the nginx configuration files that set up nginx to serve
# static client files and reverse proxy the riff api servers (data, platform, signalmaster...)
COPY conf/ /etc/nginx/
# Copy the favicon for the riffplatform
COPY favicon.ico /usr/share/nginx/html/favicon.ico
# Copy the static simulation files to be served
ADD sim.tgz /usr/share/nginx/html/sim/
# Expose both the standard http and standard https ports
EXPOSE 80 443

#
# ---- existing rtc build image ----
FROM rifflearning/rtc-build:${RTC_BUILD_TAG} AS build

#
# ---- Release ----
FROM base AS release
LABEL Description="This image is used to start the riff reverse proxy server"
# copy rtc client build artifacts to be served by nginx
COPY --from=build /app/build/ /usr/share/nginx/html/rtc/
